### ISSUE TITLE
Docker Hub docs out of sync

### ISSUE THREAD

**Issue by ahmetalpbalkan** [gliderlabs/docker-consul#105]
https://registry.hub.docker.com/u/gliderlabs/consul/

This documentation actually is for `progrium/consul:0.4` and not `gliderlabs/consul:0.5`. And these two are not compatible as far as the CLI goes.  For instance

    docker run -it gliderlabs/consul:0.5 -server -node master0 -advertise 10.0.0.4 -bootstrap-expect 3

just fails and prints Consul's usage message.

**Comment by deviantony** [comment]
Yeah what is the state of the Consul 0.5 image?

**Comment by hankerepo** [comment]
+1

**Comment by pierrebeaucamp** [comment]
+1

**Comment by jacobdr** [comment]
+1

**Comment by l8nite** [comment]
No new README yet :(

**Comment by ryanwalls** [comment]
+1

**Comment by AndreyVavilov** [comment]
+1

**Comment by mudrion** [comment]
+1

**Comment by rijnhard** [comment]
yeah seriously this needs a proper readme.

**Comment by ahmetalpbalkan** [comment]
There is now a consul official image. https://hub.docker.com/_/consul/ Closing.
