### ISSUE TITLE
check-http and check-cmd are not present

### ISSUE THREAD

**Issue by majormoses** [gliderlabs/docker-consul#106]
First off thank you for all the cool stuff. I am attempting to use a consul agent container with a checks and noticed that check-http and check-cmd are missing. I will get a PR over in a a bit.

**Comment by majormoses** [comment]
Ok looking at it more docker was removed as well. Since server pulls in agent I am not sure its a good idea to add it to the agent as its unneeded bloat; we will need it somewhere we are going to run a command or curl in the services container. what are your thoughts on this? I would be more than happy to get a PR together to help once we have an idea of what we want to do

**Comment by progrium** [comment]
Check-http is replaced with Consuls built in http checking. Check-cmd is
more complicated so it won't be built in.

On Wednesday, August 12, 2015, Ben Abrams <notifications@github.com> wrote:

> Ok looking at it more docker was removed as well. Since server pulls in
> agent I am not sure its a good idea to add it to the agent as its unneeded
> bloat; we will need it somewhere we are going to run a command or curl in
> the services container. what are your thoughts on this? I would be more
> than happy to get a PR together to help once we have an idea of what we
> want to do
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/docker-consul/issues/106#issuecomment-130191288>
> .
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by majormoses** [comment]
@progrium thanks for your reply having issues with registrator and consul ill open one over there
