### ISSUE TITLE
EC2 Node Flapping - Docker related?

### ISSUE THREAD

**Issue by djenriquez** [gliderlabs/docker-consul#109]
Hello,

Referencing [consul issue 1212](https://github.com/hashicorp/consul/issues/1212), we're seeing nodes flapping causing routes to be removed in our NGINX RP/LB by consul-template. This is causing some services to go down until the node health flaps back to healthy.

I'm wondering if this issue is related to the fact that I'm running the consul servers docker containers. Or if there is any reason to believe that running consul as an application running on the host instead of a container would cause some stability issues to go away.

Are there any negative effects, specifically related to stability, with using Consul as a docker container?

Any thoughts?

**Comment by djenriquez** [comment]
Anyone? :sweat_smile:

**Comment by djenriquez** [comment]
Opinions are welcome as well.

**Comment by mainframe** [comment]
Try run docker containers with -net host - see if it helps. If it does help then your problem might have been arp cache related probably - I think its a known problem with docker networking...

**Comment by djenriquez** [comment]
Thanks for the response @mainframe.

The problems are occuring in us-west-2 actually. After doing a really short investigation, flapping was happening in all 3 AZs.

I checked my datacenter in us-east-1 and eu-west-1 and did not see any problems with any nodes there. Although, there less than half the amount of nodes in those regions (10 in those vs 23 in us-west-2).

With known docker networking issues, sounds like itll be worth it to try installing the application directly on the host, or would `-net host` be equivalent to that in terms of networking?

**Comment by mainframe** [comment]
--net=host switches docker networking to host mode - but you still retain other docker benefits. 
Issue I was seeing with consul being inside docker and using standard docker networking was that on each container start it was given new random mac address - and that causes arp cache etc issues - ie consul nodes inter-communication will have high or 100% packet loss. We have actually public AMI in AWS Marketplace which already contains (non-flapping) dockerized consul - amongst other things. Search for NodeFabric or drop me an email to andres@opennodecloud.com and I will provide you with more detailed info about it if interested.

**Comment by djenriquez** [comment]
Thanks @mainframe, I've transitioned the consul server containers to use `--net=host` and am now slowly transitioning the agents to do the same.

I'll follow back up with you once I've done so and have seen its behavior.

**Comment by Esya** [comment]
@mainframe I'm curious because I am facing the same issue, do you force the mac address of the consul container using `-e lx` to avoid these issues?

**Comment by mainframe** [comment]
@Esya No we reverted back to host networking (ie launching containers with --net=host) - as there were too many issues with docker default networking solution - so we dropped that.

**Comment by Esya** [comment]
@mainframe I see, but then how do your containers connect to consul if they need to since 127.0.0.1 won't work? Do you use socat or iptables rules?

**Comment by mainframe** [comment]
@Esya they connect to Docker bridge IP (where Consul also binds) - which is kind of "localhost-like" static IP as well - containers will do lookup for exact docker0 interface IP during their launch through systemd service (PreStart action).

**Comment by MrMMorris** [comment]
@djenriquez just FYI, I experience consul cluster member flapping as well (I have commented on the referenced issue) and I am **NOT** running consul in containers.

**Comment by djenriquez** [comment]
Gotcha, thanks @MrMMorris. I believe its not clear that the issue is Consul related and not Docker. No flapping for me anymore, running in Docker containers.

**Comment by hamx0r** [comment]
@djenriquez what Docker Image are you using for Consul?   I'm struggling what a flapping issue on both [`progrium/consul`](https://hub.docker.com/r/progrium/consul/) and the newer [`gliderlabs/consul`](https://hub.docker.com/r/gliderlabs/consul/) Images.   When running a single server, they're fine, but when trying to cluster per the guide on the progrium image, I see the below on the Container host's `/var/log/messages` (is this what you see and mean by "flapping"?)

    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4752.941385] XFS (dm-2): Mounting V4 Filesystem
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4752.985007] XFS (dm-2): Ending clean mount
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4753.012814] XFS (dm-2): Unmounting Filesystem
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4753.091776] XFS (dm-2): Mounting V4 Filesystem
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4753.128174] XFS (dm-2): Ending clean mount
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4753.167657] XFS (dm-2): Unmounting Filesystem
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4753.210860] XFS (dm-2): Mounting V4 Filesystem
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4753.262050] XFS (dm-2): Ending clean mount
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4753.287503] device vethb56ccc1 entered promiscuous mode
    Feb 16 00:20:16 ip-10-64-21-146 kernel: [ 4753.377344] IPv6: ADDRCONF(NETDEV_UP): vethb56ccc1: link is not ready
    Feb 16 00:20:17 ip-10-64-21-146 kernel: [ 4754.147546] eth0: renamed from veth6cdf603
    Feb 16 00:20:17 ip-10-64-21-146 kernel: [ 4754.150364] IPv6: ADDRCONF(NETDEV_CHANGE): vethb56ccc1: link becomes ready
    Feb 16 00:20:17 ip-10-64-21-146 kernel: [ 4754.154524] docker0: port 1(vethb56ccc1) entered forwarding state
    Feb 16 00:20:17 ip-10-64-21-146 kernel: [ 4754.166344] docker0: port 1(vethb56ccc1) entered forwarding state
    Feb 16 00:20:17 ip-10-64-21-146 kernel: [ 4754.664507] veth6cdf603: renamed from eth0
    Feb 16 00:20:17 ip-10-64-21-146 kernel: [ 4754.669010] docker0: port 1(vethb56ccc1) entered disabled state
    Feb 16 00:20:18 ip-10-64-21-146 kernel: [ 4754.795714] docker0: port 1(vethb56ccc1) entered disabled state
    Feb 16 00:20:18 ip-10-64-21-146 kernel: [ 4754.834542] device vethb56ccc1 left promiscuous mode
    Feb 16 00:20:18 ip-10-64-21-146 kernel: [ 4754.839265] docker0: port 1(vethb56ccc1) entered disabled state
    Feb 16 00:20:18 ip-10-64-21-146 kernel: [ 4755.064778] XFS (dm-2): Unmounting Filesystem
