### ISSUE TITLE
web ui

### ISSUE THREAD

**Issue by anklos** [gliderlabs/docker-consul#112]
I am following this doc for using consul container:

https://hub.docker.com/r/progrium/consul/

I run the command `docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap -ui-dir /ui` to start a single consul server with web ui.

I find that if I set the ui dir to home directory (i.e `/home/myuser/ui`), then the `localhost:8500/ui/` returns me `404`. But if I set the ui dir to be `/ui` in the command, it works.

Could someone explain a bit please? Thanks!

**Comment by anklos** [comment]
I think because in container, `consul.json` has configured `"ui_dir": "/ui"`. But then why I still need to pass `-ui-dir` option in command to see the web ui?

**Comment by andyshinn** [comment]
Can you please try the newer `gliderlabs/consul-server` image which already has the UI in it?
