### ISSUE TITLE
Build 0.6.3 - server

### ISSUE THREAD

**Issue by sstarcher** [gliderlabs/docker-consul#128]
As of right now a fresh docker pull for gliderlabs/consul-server:0.6 gives you 0.6.2

**Comment by sstarcher** [comment]
consul:0.6 and consul-agent:0.6 are both 0.6.3

**Comment by progrium** [comment]
It must not have triggered a build. UGH docker hub.

**Comment by progrium** [comment]
Okay, triggered build for consul-server, should be 0.6.3 momentarily. Thanks for reporting.

**Comment by sstarcher** [comment]
Looks good now
