### ISSUE TITLE
Docker Hub failed to build consul-server and consul-agent against 0.6.4

### ISSUE THREAD

**Issue by ushuz** [gliderlabs/docker-consul#135]
Pull the latest image of `consul-server` and `consul-agent` from Docker Hub, then run:

```
$ docker run -d --name consul-server gliderlabs/consul-server:latest
$ docker exec consul-server /bin/consul version
Consul v0.6.3
Consul Protocol: 3 (Understands back to: 1)
```

```
$ docker run -d --name consul-agent gliderlabs/consul-agent:latest
$ docker exec consul-agent /bin/consul version
Consul v0.6.3
Consul Protocol: 3 (Understands back to: 1)
```

**Comment by CpuID** [comment]
Definitely would be nice to have resolved. Are we able to get x.y.z tags on Docker Hub? As opposed to just x.y?

**Comment by mistaka0s** [comment]
Looks like the ```gliderlabs/consul``` docker image failed to build and it used the older version of the container to build ```consul-server``` and ```consul-agent``` using 0.6.3.

Are you able to kick off a rebuild? 
https://hub.docker.com/r/gliderlabs/consul/builds/buuyepcuwhatskhhbvnwgmc/

**Comment by ianmcorvidae** [comment]
New builds have evidently been triggered and `consul-server` and `consul-agent` now both report 0.6.4. I believe this is resolved.

**Comment by ushuz** [comment]
@ianmcorvidae Indeed, the problem is resolved. I'm closing this issue.
