### ISSUE TITLE
Add a DEPRECATION notice

### ISSUE THREAD

**Issue by ahmetalpbalkan** [gliderlabs/docker-consul#143]
There is now an official image: https://hub.docker.com/_/consul/ @progrium

**Comment by jhovell** [comment]
Now that 0.7 is out, should this repo be marked as deprecated, or is someone planning to make a 0.7 build? I made a similar comment of docker hub, but looking at other unanswered comments there not sure anyone is monitoring there either.

**Comment by josegonzalez** [comment]
That's their image, not the gliderlabs image. This image still works, and while we haven't made a 0.7 release, thats just due to lack of time.
