### ISSUE TITLE
Support multiple -join ips

### ISSUE THREAD

**Issue by yaronr** [gliderlabs/docker-consul#27]
Hi

Is it possible to -join multiple ips?

**Comment by skippy** [comment]
hey @justinclayton,
would a fleet systemd file, like so: https://gist.github.com/skippy/94645f8442203dc37b5b
help?

**Comment by skozin** [comment]
+1. Multiple join IPs are useful to increase failure tolerance. Given just one IP, agent may fail to join the cluster when the target machine is down.

**Comment by progrium** [comment]
You all know you can do more joins via the API once it's booted, right?

On Sun, Jan 11, 2015 at 9:42 AM, Семён <notifications@github.com> wrote:

> +1. Multiple join IPs are useful to increase failure tolerance. Given just
> one IP, agent may fail to join the cluster when the target machine is down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/docker-consul/issues/27#issuecomment-69498583>
> .
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by justinclayton** [comment]
@progrium yes, that's how we're solving for this. Each consul server has a sidekick unit file that puts its ip into etcd and then periodically does an explicit join of the others that have already done so using docker exec. There's probably a more elegant solution somewhere, but it works for us.

**Comment by skozin** [comment]
@progrium, yes, but specifying multiple join ips when starting new agent is just much simpler when there is a fixed list of server agents with static ips. Otherwise, as @justinclayton mentioned, you'll have to use `docker exec`, [which is buggy](https://github.com/docker/docker/issues/5938) at the moment.

Anyway, thank you for all the great and inspiring work! =)

**Comment by will-ob** [comment]
:+1:

**Comment by devinrsmith** [comment]
+1

**Comment by grahamjenson** [comment]
I would really like this as well, same usecase as above systemd script that takes many ipaddress (some might be dead) and tries to join all of them. a single --join=<DEADIP> --join=<GOODIP> would be easier than looping until ew find something to join.

**Comment by hlj** [comment]
:+1:

**Comment by progrium** [comment]
You can do multiple joins or whatever Consul arguments you like now.
