### ISSUE TITLE
Honor docker --rm switch with cmd:run

### ISSUE THREAD

**Issue by mainframe** [gliderlabs/docker-consul#31]
Currently docker --rm switch for transient containers is ignored when using cmd:run approach (ie docker run --rm progrium/consul cmd:run).

**Comment by jwthomp** [comment]
Have you tried doing: `docker --rm progrium/consul cmd:run .... --rm` 

cmd:run is a short hand command that returns a text string of the form `eval docker run..` with all of the options filled out for you which you then use to to launch consul. The first --rm causes the container created for the cmd:run to be removed. You need to pass docker options after the cmd:run to have them placed in the eval string.

**Comment by progrium** [comment]
Dropped the `cmd:run` in master. Now anything is possible.
