### ISSUE TITLE
Feature Request: watch script, send HUP to named container

### ISSUE THREAD

**Issue by mgmonteleone** [gliderlabs/docker-consul#32]
We are building up an automation platform using registrator, and consul, and one use case uses a docker kill --signal=HUP sent to an nginx container to reload an automatically generated LB config, whenever a K/V is changed in consul.

We had consul implemented on the base hosts, and used a watch in consul to call a local script which sent the signal, something like
    `docker kill --signal="HUP" loadbalancer`

Would like to be able to do the same with containerized consul agents.
Since we can mount the docker socket, and the docker binary is already available, would this be as simple as creating  a new shell script such as this
   `#!/bin/bash
    docker kill --signal="HUP" loadbalancer`

Perhaps this would be more generalized, so we could pass the name of the container to be HUPED?, or perhaps even another parameter for the signal name?

Am going to proceed with this, but wondering if you have better concepts? Perhaps this is something you have already considered and rejected, or do another way?

**Comment by progrium** [comment]
Not sure this is the best way to go about it, but we dropped builtin Docker. You can still mount your host Docker binary if you need it.
