### ISSUE TITLE
Add leave_on_terminate = true to the default consul configuration

### ISSUE THREAD

**Issue by rocketraman** [gliderlabs/docker-consul#34]
When doing "docker stop" on a container, the consul process will receive a SIGTERM. However, the consul agent does not leave the cluster gracefully upon SIGTERM by default. This results in problems when the node is restarted because it is assigned a new IP address. This then triggers this bug: https://github.com/hashicorp/consul/issues/457.

By adding leave_on_terminate = true to the consul configuration in `/config/consul.json` a `docker stop` command would be treated by consul as a graceful shutdown of that agent.

**Comment by drewwells** [comment]
This would be very helpful as restarting one agent forces you to wipe all agents in the cluster.

**Comment by progrium** [comment]
Yep, adding soon.

**Comment by progrium** [comment]
Added.

**Comment by grepnull** [comment]
This didn't seem to actually get added?

**Comment by progrium** [comment]
https://github.com/gliderlabs/docker-consul/blob/master/0.5/consul-agent/config/agent.json#L4

Sorry for poor docs on the new images. Coming soon though

**Comment by grepnull** [comment]
Oh, I was looking at the server config. Is there a reason why it shouldn't be in there as well?

**Comment by progrium** [comment]
Ah. It was supposed to use consul-agent as a base, but I see it's not.
Can't remember if there was a good reason for that. Either way you're
right.

On Mon, Aug 3, 2015 at 5:39 PM, vince rosso <notifications@github.com>
wrote:

> Oh, I was looking at the server config. Is there a reason why it shouldn't
> be in there as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/docker-consul/issues/34#issuecomment-127424424>
> .
>



-- 
Jeff Lindsay
http://progrium.com
