### ISSUE TITLE
Failed to check for updates

### ISSUE THREAD

**Issue by lgs** [gliderlabs/docker-consul#38]
What is that "Failed to check for updates" to the last line ?

<pre>
lsoave@basenode:~$ sudo docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'node1'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 0.0.0.0 (HTTP: 8500, DNS: 53, RPC: 8400)
      Cluster Addr: 172.17.0.3 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2014/11/21 23:30:14 [INFO] serf: EventMemberJoin: node1 172.17.0.3
    2014/11/21 23:30:14 [INFO] serf: EventMemberJoin: node1.dc1 172.17.0.3
    2014/11/21 23:30:14 [INFO] raft: Node at 172.17.0.3:8300 [Follower] entering Follower state
    2014/11/21 23:30:14 [INFO] consul: adding server node1 (Addr: 172.17.0.3:8300) (DC: dc1)
    2014/11/21 23:30:14 [INFO] consul: adding server node1.dc1 (Addr: 172.17.0.3:8300) (DC: dc1)
    2014/11/21 23:30:14 [ERR] agent: failed to sync remote state: No cluster leader
    2014/11/21 23:30:15 [WARN] raft: Heartbeat timeout reached, starting election
    2014/11/21 23:30:15 [INFO] raft: Node at 172.17.0.3:8300 [Candidate] entering Candidate state
    2014/11/21 23:30:16 [INFO] raft: Election won. Tally: 1
    2014/11/21 23:30:16 [INFO] raft: Node at 172.17.0.3:8300 [Leader] entering Leader state
    2014/11/21 23:30:16 [INFO] consul: cluster leadership acquired
    2014/11/21 23:30:16 [INFO] consul: New leader elected: node1
    2014/11/21 23:30:16 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2014/11/21 23:30:16 [INFO] consul: member 'node1' joined, marking health alive
    2014/11/21 23:30:16 [INFO] agent: Synced service 'consul'
==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=linux&signature=4f33e3ab-7ef7-7220-5d0d-4844e9a08500&version=0.4.1: x509: failed to load system roots and no roots provided

</pre>

**Comment by skippy** [comment]
nm; I see #28
