### ISSUE TITLE
Docker 1.4.0

### ISSUE THREAD

**Issue by sstarcher** [gliderlabs/docker-consul#39]
If I up my container with docker 1.4.0 I get the following error

```
consul_1 | ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
consul_1 | ==> Starting Consul agent...
consul_1 | ==> Starting Consul agent RPC...
consul_1 | ==> Joining cluster...
consul_1 | ==> Reading remote state failed: EOF
opt_consul_1 exited with code 1
```

If I downgrade to 1.3.3 and re-run the container it works

**Comment by peebles** [comment]
I am seeing the same problem, using docker 1.5.0.

My consul cluster:
vagrant@consul01:~$ consul members
Node               Address           Status  Type    Build  Protocol
consul-master-1    192.168.2.2:8301  alive   server  0.4.0  2
consul-follower-1  192.168.2.3:8301  alive   client  0.4.0  2
consul-follower-2  192.168.2.4:8301  alive   client  0.4.0  2

and the docker command I am running:
$ docker run  -p 8300:8300 -p 8301:8301 -p 8301:8301/udp -p 8302:8302 -p 8302:8302/udp -p 8400:8400 -p 8500:8500 -p 8600:8600/udp --name discovery03 -h discovery03 progrium/consul -rejoin -advertise 192.168.2.7 -join 192.168.2.3
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
==> Reading remote state failed: EOF
