### ISSUE TITLE
AWS example

### ISSUE THREAD

**Issue by skippy** [gliderlabs/docker-consul#43]
would it be worth adding documentation on how to run on AWS, like you've done with boot2docker for OSX?  I may have gotten completely mixed up, but this ended up working for me:

```bash
docker --daemon \
   	   --host=fd:// \
	   --dns 172.17.42.1 \
	   --dns $(awk '/^nameserver/{print $2}' /etc/resolv.conf) \
	   --dns-search service.consul \
	   $DOCKER_OPTS
```

the first `--dns` is docker0 veth, so the value tends to default to `172.17.42.1`.  The 2nd `--dns` gets the aws provided nameserver.  If you don't set this up, and use `8.8.8.8` per the documentation, you need to open up the `:53` ports on the AWS VPC security groups and network acls.  

@progrium what do you think?  If this smells right, I'll submit a PR to add this to the `README.md`

thanks!

EDIT: removed `--dns $(ip ro | awk '/docker0/{print $9}')` and replaced with `--dns 172.17.42.1` as the docker0 bridge doesn't exist on initial boot

**Comment by NoumanSaleem** [comment]
I don't think you'd get the expected results since the consul recursor is hardcoded as 8.8.8.8
https://github.com/progrium/docker-consul/blob/master/config/consul.json#L8

**Comment by skippy** [comment]
yep!  I had to overload that as well.  The other option is to open up port 53 on your security groups and network acls to the VPC NAT instance.  Again, that probably would be worth adding into the docs, don't you think?

**Comment by NoumanSaleem** [comment]
For now, until consul allows a cli --recursor flag, I've set my recursor as `dnsmasq` and am linking a dnsmasq container on docker run -link dnsmasq:dnsmasq. The dnsmasq container uses resolv.conf (from the host as docker provides) which resolves to the VPC dns.

**Comment by progrium** [comment]
We'll be adding an example using Terraform to run on AWS. Latest version doesn't have a buitlin recursor. We don't recommend using Consul for recursive lookups and instead putting it behind something like dnsmasq or resolvable.
