### ISSUE TITLE
health interval ignored

### ISSUE THREAD

**Issue by murphydanger** [gliderlabs/docker-consul#49]
NB: cross posed in the [consul google group](https://groups.google.com/forum/#!forum/consul-tool) and [`progrium/registrator#97`](https://github.com/progrium/registrator/issues/97), for consistency.

It seems as though any health check I register, be it through the agent (attached to a service) or though the catalog), or even through [`progrium/registrator`](https://github.com/progrium/registrator) leads to a health check interval that is seemingly ignored.

E.g.
```sh
curl --include --request PUT --data-binary "{
\"ID\": \"nginx1\",
\"Name\": \"nginx\",
\"Port\": 80,
\"Check\": {
    \"Name\": \"Nginx health check\",
    \"Notes\": \"Script based health check\",
    \"Status\": \"unknown\",
    \"Script\": \"curl $IP/webhook/health\",
    \"Interval\": \"1m\"
}
}" $IP:8500/v1/agent/service/register
```
This service will get hit on `/webhook/health` every five minutes, instead of one minute (or whatever value of `Interval` I happen to set).

**Comment by jonathanepollack** [comment]
Status update: `consul` has a setting ([`check_update_interval`](http://www.consul.io/docs/agent/options.html#check_update_interval)) for the refresh interval of the output, which defaults to 300 seconds.

I wasn't able to effect any changes (i.e. I would change it's value to `0s` or even `5s` in the `consul.json`, but that didn't do anything.) This seems like an issue with `consul` or `docker-consul`. I need to change the release version of `consul` to double check this.

**Comment by jonathanepollack** [comment]
A good way to check that this value is actually being set is to curl `http://${AGENT_IP}:8500/v1/agent/self?pretty=1`, and look for the “Config” ->
“CheckUpdateInterval” key. It's default will be 5 minutes.

**Comment by progrium** [comment]
Not sure what it would be with the Docker image. Lots has changed since this though. Maybe the image or Consul itself has resolved this issue. Open again if still experiencing.

**Comment by sergeevii123** [comment]
eventually worked for my container:
docker run... "-e SERVICE_CHECK_HTTP=/health " +
"-e SERVICE_CHECK_INTERVAL=1s " 
in docker consul logs:
2016/02/17 07:00:20 [WARN] agent: http request failed 'http://10.199.51.164:7070/health': Get http://10.199.51.164:7070/health: read tcp 10.199.51.164:7070: connection reset by peer
    2016/02/17 07:00:21 [WARN] agent: http request failed 'http://10.199.51.164:7070/health': Get http://10.199.51.164:7070/health: read tcp 10.199.51.164:7070: connection reset by peer
    2016/02/17 07:00:22 [WARN] agent: http request failed 'http://10.199.51.164:7070/health': Get http://10.199.51.164:7070/health: read tcp 10.199.51.164:7070: connection reset by peer
    2016/02/17 07:00:23 [WARN] agent: http request failed 'http://10.199.51.164:7070/health': Get http://10.199.51.164:7070/health: net/http: transport closed before response was received
    2016/02/17 07:00:24 [WARN] agent: http request failed 'http://10.199.51.164:7070/health': Get http://10.199.51.164:7070/health: read tcp 10.199.51.164:7070: connection reset by peer
    2016/02/17 07:00:25 [WARN] agent: http request failed 'http://10.199.51.164:7070/health': Get http://10.199.51.164:7070/health: read tcp 10.199.51.164:7070: connection reset by peer
