### ISSUE TITLE
Consul doesn't leave cluster when stopping container

### ISSUE THREAD

**Issue by johnrengelman** [gliderlabs/docker-consul#52]
Even if specifying `leave_on_terminate` in the Consul configuration (https://github.com/progrium/docker-consul/issues/34).

When stopping the container, the consul agent does not gracefully leave the cluster. It appears to be with the `start` script no propagating the signals to the Consul process (I think).

**Comment by progrium** [comment]
Fixed.

**Comment by csakoda** [comment]
@progrium Where is this patched?  Or is it just fixed by virtue of no longer using /bin/start at all on `master` ?

**Comment by progrium** [comment]
Yeah, the consul-agent and consul-server both include leave_on_terminate in their default config.

**Comment by leshik** [comment]
There is one case when this might be harmful. Suppose you have a cluster of 3 nodes and you need to reboot all of them simultaneously. If leave_on_terminate is true, all 3 nodes leave cluster and then you have to manually rejoin. I think this option is ok for agents but should be off for servers.

**Comment by csakoda** [comment]
@leshik Why should you need to reboot your whole cluster simultaneously?  In a production scenario, I'd only expect consul cluster nodes to go down in response to availability events, and if properly distributed across AZ (in AWS, for example), that should only be happening on 1 of the 3 at a given time.

**Comment by leshik** [comment]
@csakoda I agree, this shouldn't happen in production. I encountered this in my development environment. Unfortunately, there is no command-line option for leave_on_terminate config setting.
