### ISSUE TITLE
started docker container is unreachable.

### ISSUE THREAD

**Issue by johanatan** [gliderlabs/docker-consul#53]
Jonathans-MacBook-Pro:servicetown jonathan$ docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap
    ==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
    ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
    ==> Starting Consul agent...

==================== FROM ANOTHER SHELL ==========================

    Jonathans-MacBook-Pro:servicetown jonathan$ curl localhost:8500/v1/catalog/nodes
    curl: (7) Failed to connect to localhost port 8500: Connection refused

**Comment by tusbar** [comment]
If you’re using boot2docker, you need to `curl $(boot2docker ip):8500/v1/catalog/nodes`.
