### ISSUE TITLE
Create consul-0.5 on docker hub

### ISSUE THREAD

**Issue by lalyos** [gliderlabs/docker-consul#55]
`latest` tag at https://registry.hub.docker.com/u/progrium/consul/ was following amazing quickly the new release of consul 0.5.0. thanks for that!

Would be nice to be able to reference explicitly by tag `docker pull progrium/consul:consul-0.5`

**Comment by justinclayton** [comment]
+1

**Comment by roobert** [comment]
+1

**Comment by progrium** [comment]
We now have a `0.5` version on the gliderlabs repo. `latest` points to `0.5`. Keep in mind the image has been split into several different roles/profiles.
