### ISSUE TITLE
Dependent docker images fail to build without config directory

### ISSUE THREAD

**Issue by gdhaworth** [gliderlabs/docker-consul#57]
The `ONBUILD ADD ./config /config/` instruction in the `Dockerfile` forces child `Dockerfile`s to have their own `config` directory. This makes sense in most cases which follow the common pattern of including configuration files in a dependent image. The problem is that this prevents dependent images that are not making any changes to `config` from being built since the `ONBUILD` trigger doesn't look like it can be turned off. My example is in building an image with a specific version of Docker (right now this image has Docker 1.5.0 and CoreOS's stable release is only up to 1.4.1).

I would argue that users who want to attach their own configs to an image will know they need a command for that and won't easily miss using their own `ADD`/`COPY` statement. Since the cost of having the `ONBUILD` trigger is preventing other use cases from building without a workaround I ask that you consider removing it.

**Comment by progrium** [comment]
Good point. I'll work that into a new version.

**Comment by progrium** [comment]
Removed in latest. Thanks.
