### ISSUE TITLE
client and server don't have same version

### ISSUE THREAD

**Issue by outrunthewolf** [gliderlabs/docker-consul#60]
Any idea what this means?

```sh
Error response from daemon: client and server don't have same version (client : 1.17, server: 1.15)Error response from daemon: client and server don't have same version (client : 1.17, server: 1.15)docker: "run" requires a minimum of 1 argument. See 'docker run --help'.
```

I get it when I use the "check-cmd {container_name}".

**Comment by Darwiner** [comment]
I'm getting the same issue.  Basically, seems the host is running a version of docker older than the docker binary included in the container...

In my case, with CoreOS:

Container:

# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64

Host:

$ docker version                                                                                                                                                          
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8-dirty
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8-dirty

**Comment by AshleyAitken** [comment]
Similar (same?) problem on Debian with backports:

sudo docker images
FATA[0000] Error response from daemon: client and server don't have same version (client : 1.17, server: 1.16) 

Any suggestions how to update server please?

**Comment by ashw7n** [comment]
installed kitematics, and it brought in the latest version of docker I suspect. anyways getting this error after this.

**Comment by lbpierre** [comment]
I ran into the same issue, because I did not install correctly docker. I fixed my problem, I re-installed docker by this way:
sudo wget -qO- https://get.docker.com/ | sh 

Hope it help someone.

**Comment by progrium** [comment]
We dropped support for builtin Docker, however you can still bind mount your host docker binary in if you need it in shell scripts.
