### ISSUE TITLE
check_http closes connection before full response is read

### ISSUE THREAD

**Issue by johnrengelman** [gliderlabs/docker-consul#63]
I am not a `curl` expert by any means, but when testing using the `check_http` command, I'm seeing a number of exceptions in my spring-boot application related to the health check.

The exceptions are the result of a broken pipe when trying to write the error response when the health check is failing. I can't replicate the issue when testing from my host machine and when running the healthcheck using the Consul container.

I found that if I removed the `--fail` option from the `curl` command, the exceptions would go away when the health check ran. Alternatively I can leave the `--fail` and add a `&& sleep 1` to the end of the bash command in `check-http`.

So it appears that with the `--fail` option, `curl` is returning before the entire response has been read, which allows the Docker container to shutdown, thus closing the connection, resulting in the broken pipe.

**Comment by progrium** [comment]
Dropped check-http since Consul now supports native HTTP checks.
