### ISSUE TITLE
Consul 0.5.1 to Docker Hub

### ISSUE THREAD

**Issue by ghicks-rmn** [gliderlabs/docker-consul#82]
This repo has been updated to use Consul 0.5.1, but the progrium/consul:latest image on Docker Hub still has 0.5.0. Can we get 0.5.1 pushed up as latest?

**Comment by jakubwierzbowski** [comment]
:+1: for this request!

**Comment by holgerstolzenberg** [comment]
+1

**Comment by drewwells** [comment]
@progrium any update on this?

**Comment by progrium** [comment]
Odd, automated builds are working. Whatever is here should be up there.

**Comment by progrium** [comment]
Since moving to gliderlabs, we rewrote the image, broke it into different images, and included Consul versions in the image repo. So now everything is tagged. Build triggers / links are also set up so the base consul image will trigger rebuilding agent and server.

Btw, latest is 0.5.2
