### ISSUE TITLE
Tag images with consul version on docker hub

### ISSUE THREAD

**Issue by cap10morgan** [gliderlabs/docker-consul#89]
It would be awesome if these images were tagged with the version of consul they contained on Docker Hub.

So the current latest (as of 2015-6-4) should be tagged as `progrium/consul:0.5.2`.

This would make it much easier to control which version of Consul you're running when using this image.

**Comment by jeffcharles** [comment]
+1

**Comment by voidengineer** [comment]
+1

**Comment by progrium** [comment]
Done. However, more has changed. This github repo manages three Docker Hub images: `gliderlabs/consul`, `gliderlabs/consul-agent`, and gliderlabs/consul-server`. Each one currently has a `latest` tag and `0.5` tag that currently point to the same thing. Minor revisions will roll into minor versions for now.

**Comment by cap10morgan** [comment]
@progrium Thanks! This is helpful.

But it would be great to have the patch version number in the tags too. I want to be able to specify in my downstream Dockerfile whether I'm starting with consul 0.5.0 or 0.5.2, for example. Is there a reason you're not including that (for now)?

**Comment by progrium** [comment]
I'd just rather not maintain that level of granularity. But maybe I can do it with branches... thing is, any update is going to require changes to Docker Hub and that's not something somebody can submit a PR for.
