### ISSUE TITLE
POST health check json having multiple services

### ISSUE THREAD

**Issue by sourav82** [gliderlabs/docker-consul#91]
I was wondering how to specify multiple service health check configuration in a single JSON.

I was trying with below JSON -

```json
{
  "Checks": [{"Name": "WebApp",
  "Script": "/bin/script.sh",
  "ServiceID": "registrator:dreamy_payne:5000",
  "ServiceName": "webapp",
  "Interval": "10s"
},
{
  "Name": "registry",
  "Script": "/bin/script.sh",
  "ServiceID": "registrator:registry:5000",
  "ServiceName": "registry",
  "Interval": "10s"
}]
}
```
It gives error- not able to parse multiple services in a single json.
Could anyone please clarify what should be the exact way here?

**Comment by progrium** [comment]
Not sure. Please refer to Consul docs: https://consul.io/docs/agent/checks.html
If you continue having an issue, I suggest opening an issue with Consul.
