### ISSUE TITLE
Passing Data center variable as an argument to Consul.

### ISSUE THREAD

**Issue by ashish235** [gliderlabs/docker-consul#92]
Hi,

Can this be expected in future release? or this is already in place because I couldn't find any documentation for the same.

My consul-docker crashes when I pass any attribute with -dc flag. 

Thanks.

**Comment by progrium** [comment]
Can you provide an example?

**Comment by ashish235** [comment]
@progrium, Consul is data-center away, that's what I know. So there should be an way of passing an argument while starting a consul agent or server to let it know which datacenter it belongs to. 

For eg. I 've 2 data centers and they are part of one single cluster, now I want to perform some operations only on DC1 and not DC2. So I want some agents/servers to be running with DC2 flag.

Please let me know, if I made myself clear? if now I will try harder ;)

**Comment by mgood** [comment]
@ashish235 you mentioned in the post that consul crashes when you pass the -dc flag. I think @progrium was asking for an example of the consul command and error you encountered. Since the Docker container just wraps the consul command you should be able to pass it the same arguments.

**Comment by ashish235** [comment]
@mgood, the command was with -dc DC2. appended to it before the image name. 

![image](https://cloud.githubusercontent.com/assets/11647730/8450906/9029247e-1ffc-11e5-9913-50bbcc630515.png)

Can you please help me with the command? I mean the flag name because -dc seems to be not working.

**Comment by mgood** [comment]
Ok, but what was the error message from consul?

**Comment by ashish235** [comment]
It's working. I was having a consul with DC2 config trying to join a consul from DC1. Maybe that is not allowed. I think I need to revisit the data-center aware documentation for Consul.

Thanks for the help.
